package MetaC::HIR::NodeRegistry::OperationsData;
use strict;
use warnings;
use Exporter 'import';

use MetaC::TypeSpec qw(sequence_type_for_element);

our @EXPORT_OK = qw(operation_registry);

my %REGISTRY = (
    calls => {
        user => {
            op_id => 'call.user.v1', backend_emitter => 'call.user.v1',
            fluent_invocation => {
                enabled           => 1,
                min_param_count   => 1,
                receiver_position => 0,
            },
        },
        builtins => {
            parseNumber => {
                op_id         => 'call.builtin.parseNumber.v1', backend_emitter => 'call.builtin.parseNumber.v1',
                param_policy  => 'fixed',
                param_symbols => ['string'],
                result_policy => 'fixed',
                result_type   => 'number | error',
            },
            error => {
                op_id         => 'call.builtin.error.v1', backend_emitter => 'call.builtin.error.v1',
                param_policy  => 'fixed',
                param_symbols => ['any'],
                result_policy => 'fixed',
                result_type   => 'error',
            },
            max => {
                op_id         => 'call.builtin.max.v1', backend_emitter => 'call.builtin.max.v1',
                param_policy  => 'fixed',
                param_symbols => ['number', 'number'],
                result_policy => 'fixed',
                result_type   => 'number',
            },
            min => {
                op_id         => 'call.builtin.min.v1', backend_emitter => 'call.builtin.min.v1',
                param_policy  => 'fixed',
                param_symbols => ['number', 'number'],
                result_policy => 'fixed',
                result_type   => 'number',
            },
            last => {
                op_id         => 'call.builtin.last.v1', backend_emitter => 'call.builtin.last.v1',
                param_policy  => 'fixed',
                param_symbols => ['any'],
                result_policy => 'fixed',
                result_type   => 'number',
            },
            seq => {
                op_id         => 'call.builtin.seq.v1', backend_emitter => 'call.builtin.seq.v1',
                param_policy  => 'fixed',
                param_symbols => ['number', 'number'],
                result_policy => 'fixed',
                result_type   => sequence_type_for_element('number'),
            },
            split => {
                op_id         => 'call.builtin.split.v1', backend_emitter => 'call.builtin.split.v1',
                param_policy  => 'fixed',
                param_symbols => ['string', 'string'],
                result_policy => 'fixed',
                result_type   => sequence_type_for_element('string') . ' | error',
            },
            lines => {
                op_id         => 'call.builtin.lines.v1', backend_emitter => 'call.builtin.lines.v1',
                param_policy  => 'fixed',
                param_symbols => ['string'],
                result_policy => 'fixed',
                result_type   => sequence_type_for_element('string') . ' | error',
            },
            log => {
                op_id         => 'call.builtin.log.v1', backend_emitter => 'call.builtin.log.v1',
                param_policy  => 'fixed',
                param_symbols => ['any'],
                result_policy => 'arg0',
            },
            __default__ => {
                op_id         => 'call.builtin.unknown.v1', backend_emitter => 'call.builtin.unknown.v1',
                param_policy  => 'unknown',
                result_policy => 'unknown',
            },
        },
    },
    methods => {
        size      => { op_id => 'method.size.v1', backend_emitter => 'method.size.v1',      receiver_policy => 'sized',                    param_policy => 'size_by_receiver',   result_policy => 'fixed',             result_type => 'number',              fallibility => 'never', length_semantics => 1, matrix_axis_argument => 1 },
        count     => { op_id => 'method.count.v1', backend_emitter => 'method.count.v1',     receiver_policy => 'sized',                    param_policy => 'none',               result_policy => 'fixed',             result_type => 'number',              fallibility => 'never', length_semantics => 1 },
        chars     => { op_id => 'method.chars.v1', backend_emitter => 'method.chars.v1',     receiver_policy => 'string',                   param_policy => 'none',               result_policy => 'fixed',             result_type => sequence_type_for_element('string'),                    fallibility => 'never' },
        chunk     => { op_id => 'method.chunk.v1', backend_emitter => 'method.chunk.v1',     receiver_policy => 'string',                   param_policy => 'fixed',              param_type_symbols => ['number'],     result_policy => 'fixed',             result_type => sequence_type_for_element('string'),                    fallibility => 'never' },
        isBlank   => { op_id => 'method.isBlank.v1', backend_emitter => 'method.isBlank.v1',   receiver_policy => 'string',                   param_policy => 'none',               result_policy => 'fixed',             result_type => 'bool',                fallibility => 'never' },
        split     => { op_id => 'method.split.v1', backend_emitter => 'method.split.v1',     receiver_policy => 'string',                   param_policy => 'fixed',              param_type_symbols => ['string'],     result_policy => 'fixed',             result_type => sequence_type_for_element('string') . ' | error',      fallibility => 'always', tags => ['fallible_diag_split'] },
        match     => { op_id => 'method.match.v1', backend_emitter => 'method.match.v1',     receiver_policy => 'string',                   param_policy => 'fixed',              param_type_symbols => ['string'],     result_policy => 'fixed',             result_type => sequence_type_for_element('string') . ' | error',      fallibility => 'always' },
        compareTo => { op_id => 'method.compareTo.v1', backend_emitter => 'method.compareTo.v1', receiver_policy => 'default_comparison',       param_policy => 'fixed',              param_type_symbols => ['receiver'],   result_policy => 'fixed',             result_type => 'comparison_result',   fallibility => 'never' },
        andThen   => { op_id => 'method.andThen.v1', backend_emitter => 'method.andThen.v1',   receiver_policy => 'comparison_result',        param_policy => 'fixed',              param_type_symbols => ['comparison_result'], result_policy => 'fixed',       result_type => 'comparison_result',   fallibility => 'never' },
        push      => { op_id => 'method.push.v1', backend_emitter => 'method.push.v1',      receiver_policy => 'sequence',                 param_policy => 'fixed',              param_type_symbols => ['receiver_elem'], result_policy => 'fixed',        result_type => 'number',              fallibility => 'never', tags => ['mutates_receiver', 'requires_nested_size_push_proof'] },
        any       => {
            op_id => 'method.any.v1', backend_emitter => 'method.any.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'fixed',
            result_type => 'bool',
            fallibility => 'contextual',
            tags => ['try_const_assignment_unsupported', 'enforce_callback_lambda_shape'],
            callback_shape_label => 'any(...) predicate must be a single-parameter lambda',
            callback_contract => {
                total_arg_count => 1,
                callback_arg_index => 0,
                callback_arity => 1,
                param_type_symbols => ['elem'],
                return_type_symbol => 'bool',
            },
        },
        all       => {
            op_id => 'method.all.v1', backend_emitter => 'method.all.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'fixed',
            result_type => 'bool',
            fallibility => 'contextual',
            tags => ['try_const_assignment_unsupported', 'enforce_callback_lambda_shape'],
            callback_shape_label => 'all(...) predicate must be a single-parameter lambda',
            callback_contract => {
                total_arg_count => 1,
                callback_arg_index => 0,
                callback_arity => 1,
                param_type_symbols => ['elem'],
                return_type_symbol => 'bool',
            },
        },
        max       => { op_id => 'method.max.v1', backend_emitter => 'method.max.v1',       receiver_policy => 'sequence',                 param_policy => 'none',               result_policy => 'traceable_member',  fallibility => 'never', string_elem_result_type => 'number' },
        last      => { op_id => 'method.last.v1', backend_emitter => 'method.last.v1',      receiver_policy => 'sequence',                 param_policy => 'none',               result_policy => 'traceable_member',  fallibility => 'conditional', tags => ['conditional_sequence_requires_known_size'] },
        sort      => { op_id => 'method.sort.v1', backend_emitter => 'method.sort.v1',      receiver_policy => 'sequence_orderable',       param_policy => 'none',               result_policy => 'receiver',          fallibility => 'never' },
        map       => {
            op_id => 'method.map.v1', backend_emitter => 'method.map.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'receiver',
            dynamic_result_policy => 'mapped_sequence',
            fallibility => 'contextual',
            tags => ['fallible_diag_mapper'],
            callback_contract => {
                total_arg_count => 1,
                callback_arg_index => 0,
                callback_arity => 1,
                param_type_symbols => ['elem'],
                return_type_symbol => 'any',
            },
        },
        slice     => { op_id => 'method.slice.v1', backend_emitter => 'method.slice.v1',     receiver_policy => 'sequence',                 param_policy => 'fixed',              param_type_symbols => ['number'],     result_policy => 'receiver',          fallibility => 'conditional', tags => ['conditional_sequence_infallible'] },
        filter    => {
            op_id => 'method.filter.v1', backend_emitter => 'method.filter.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'receiver',
            dynamic_result_policy => 'receiver',
            fallibility => 'contextual',
            tags => ['entailment_filter_receiver_elem_supported'],
            callback_contract => {
                total_arg_count => 1,
                callback_arg_index => 0,
                callback_arity => 1,
                param_type_symbols => ['elem'],
                return_type_symbol => 'bool',
            },
        },
        sortBy    => {
            op_id => 'method.sortBy.v1', backend_emitter => 'method.sortBy.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'receiver',
            fallibility => 'contextual',
            callback_contract => {
                total_arg_count => 1,
                callback_arg_index => 0,
                callback_arity => 2,
                param_type_symbols => ['elem', 'elem'],
                return_type_symbol => 'comparison_result',
            },
        },
        insert    => { op_id => 'method.insert.v1', backend_emitter => 'method.insert.v1',    receiver_policy => 'sequence_or_matrix',       param_policy => 'insert_by_receiver', result_policy => 'receiver',          fallibility => 'matrix_insert', tags => ['mutates_receiver', 'conditional_sequence_requires_known_size', 'fallible_diag_insert_matrix_unconstrained', 'entailment_insert_sequence_index_literal_if_size_known', 'entailment_insert_matrix_index_proof_if_size_known'] },
        at        => { op_id => 'method.at.v1', backend_emitter => 'method.at.v1',        receiver_policy => 'matrix',                   param_policy => 'fixed',              param_type_symbols => ['number_list'], result_policy => 'matrix_elem',      fallibility => 'never' },
        log       => { op_id => 'method.log.v1', backend_emitter => 'method.log.v1',       receiver_policy => 'any',                      param_policy => 'none',               result_policy => 'receiver',          fallibility => 'never' },
        members   => { op_id => 'method.members.v1', backend_emitter => 'method.members.v1',   receiver_policy => 'matrix',                   param_policy => 'none',               result_policy => 'matrix_members',    fallibility => 'never' },
        index     => { op_id => 'method.index.v1', backend_emitter => 'method.index.v1',     receiver_policy => 'sequence_member_or_matrix_member', param_policy => 'none',         result_policy => 'index_by_receiver', fallibility => 'never', traceability => 'requires_source_index_metadata' },
        neighbours => { op_id => 'method.neighbours.v1', backend_emitter => 'method.neighbours.v1', receiver_policy => 'matrix_or_member',        param_policy => 'neighbours_by_receiver', result_policy => 'matrix_neighbours', fallibility => 'never', traceability => 'requires_source_matrix_member_metadata' },
        reduce    => {
            op_id => 'method.reduce.v1', backend_emitter => 'method.reduce.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'unknown',
            dynamic_result_policy => 'initial',
            fallibility => 'contextual',
            tags => ['try_const_assignment_unsupported', 'enforce_callback_lambda_shape'],
            callback_shape_label => 'reduce(...) second arg must be a two-parameter lambda',
            callback_contract => {
                total_arg_count => 2,
                initial_arg_index => 0,
                initial_type_policy => 'any_valid',
                callback_arg_index => 1,
                callback_arity => 2,
                param_type_symbols => ['initial', 'elem'],
                return_type_symbol => 'initial',
            },
        },
        assert    => {
            op_id => 'method.assert.v1', backend_emitter => 'method.assert.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'receiver',
            dynamic_result_policy => 'receiver_with_error',
            fallibility => 'always',
            tags => ['try_const_assignment_unsupported', 'enforce_callback_lambda_shape'],
            callback_shape_label => 'assert(...) first arg must be a single-parameter lambda predicate',
            callback_contract => {
                total_arg_count => 2,
                callback_arg_index => 0,
                callback_arity => 1,
                param_type_symbols => ['receiver'],
                return_type_symbol => 'bool',
            },
        },
        scan      => {
            op_id => 'method.scan.v1', backend_emitter => 'method.scan.v1',
            receiver_policy => 'sequence',
            param_policy => 'callback_contract',
            result_policy => 'receiver',
            dynamic_result_policy => 'sequence_of_initial',
            fallibility => 'contextual',
            tags => ['try_const_assignment_unsupported'],
            callback_contract => {
                total_arg_count => 2,
                initial_arg_index => 0,
                initial_type_policy => 'elem',
                callback_arg_index => 1,
                callback_arity => 2,
                param_type_symbols => ['elem', 'elem'],
                return_type_symbol => 'elem',
            },
        },
        __default__ => { op_id => 'method.unknown.v1', backend_emitter => 'method.unknown.v1', receiver_policy => 'none',                     param_policy => 'unknown',            result_policy => 'unknown',           fallibility => 'never' },
    },
);

sub operation_registry { return \%REGISTRY; }

1;
